### ISSUE TITLE
Develop additional modules for the full day course

### ISSUE THREAD

**Issue by pansapiens** [MonashDataFluency/python-workshop-base#10]
There some partial modules in `workshops/docs/modules/notebooks/wip` - in particular, `functions` and `slicing_and_list_comprehensions` aren't already covered in detail in the existing modules and are  the most developed so snippets far.

The BLAST and text parsing module from [here](https://monashbioinformaticsplatform.github.io/intro-to-python-for-bioinformatics/01_Intro.html) could also be tweaked to fit the format of these workshops and included in full day workshops targeted at biosciences researchers.

**Comment by anupshah14** [comment]
- Separate data related modules such as `joining dataframes`, `missing values` and `data types in pandas` could be used. At the moment `data types` are combined with `data analysis in python` module and `missing values` in indexing and slicing section.

**Comment by anupshah14** [comment]
Total 9 modules are created including 3 new modules

- Functions

- Dataframe Joints

- Defensive Programming

**Comment by pansapiens** [comment]
Appears we have more than a full day's worth of lessons now, in practise.
